-- MySQL Script generated by MySQL Workbench
-- 09/10/15 21:50:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbFono
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbFono
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbFono` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbFono` ;

-- -----------------------------------------------------
-- Table `dbFono`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbFono`.`laboratorio` (
  `lab_id` INT NOT NULL COMMENT '',
  `lab_nombre` VARCHAR(45) NULL COMMENT '',
  `lab_encargado` VARCHAR(45) NULL COMMENT '',
  `rut` INT NULL COMMENT '',
  PRIMARY KEY (`lab_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFono`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbFono`.`profesor` (
  `prof_id` INT NOT NULL COMMENT '',
  `laboratorio_idlaboratorio` INT NOT NULL COMMENT '',
  `prof_nombre` VARCHAR(45) NOT NULL COMMENT '',
  `prof_pass` VARCHAR(45) NOT NULL COMMENT '',
  `prof_esp` INT NOT NULL COMMENT '',
  PRIMARY KEY (`prof_id`)  COMMENT '',
  INDEX `fk_profesor_laboratorio1_idx` (`laboratorio_idlaboratorio` ASC)  COMMENT '',
  CONSTRAINT `fk_profesor_laboratorio1`
    FOREIGN KEY (`laboratorio_idlaboratorio`)
    REFERENCES `dbFono`.`laboratorio` (`lab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFono`.`anamnesis_lenguaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbFono`.`anamnesis_lenguaje` (
  `anl_id` INT NOT NULL COMMENT '',
  `anl_nombre` VARCHAR(45) NULL COMMENT '',
  `anl_fecha_nacimiento` DATETIME NULL COMMENT '',
  `anl_edad` INT NULL COMMENT '',
  `anl_idioma` VARCHAR(45) NULL COMMENT '',
  `anl_direccion` VARCHAR(45) NULL COMMENT '',
  `anl_numfon` INT NULL COMMENT '',
  `anl_estado_civil` VARCHAR(45) NULL COMMENT '',
  `anl_hijos` INT NULL COMMENT '',
  `anl_con_quien_vive` VARCHAR(45) NULL COMMENT '',
  `anl_fam_acompañante` VARCHAR(45) NULL COMMENT '',
  `anl_derivado_p` VARCHAR(45) NULL COMMENT '',
  `anl_fecha_evaluacion` DATETIME NULL COMMENT '',
  `anl_escolaridad` VARCHAR(45) NULL COMMENT '',
  `anl_desempeño_escolar` INT NULL COMMENT '',
  `anl_mejor_desempeño` VARCHAR(45) NULL COMMENT '',
  `anl_peor_desempeño` VARCHAR(45) NULL COMMENT '',
  `anl_escolaridad_padres` VARCHAR(45) NULL COMMENT '',
  `anl_profesion_oficio` VARCHAR(45) NULL COMMENT '',
  `anl_perferc` VARCHAR(45) NULL COMMENT '',
  `anl_años_perfec` VARCHAR(45) NULL COMMENT '',
  `anl_ocupacion_prev` VARCHAR(45) NULL COMMENT '',
  `anl_situacion_queja` VARCHAR(45) NULL COMMENT '',
  `anl_situacion_act` VARCHAR(45) NULL COMMENT '',
  `anl_habilidad_no` VARCHAR(45) NULL COMMENT '',
  `anl_actividades_previ` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`anl_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFono`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbFono`.`paciente` (
  `pac_rut` INT NOT NULL COMMENT '',
  `pac_nombre` VARCHAR(45) NULL COMMENT '',
  `pac_apellido` VARCHAR(45) NULL COMMENT '',
  `profesor_prof_id` INT NOT NULL COMMENT '',
  `anamnesis_lenguaje_anl_id` INT NOT NULL COMMENT '',
  `laboratorio_idlaboratorio` INT NOT NULL COMMENT '',
  PRIMARY KEY (`pac_rut`)  COMMENT '',
  INDEX `fk_paciente_profesor_idx` (`profesor_prof_id` ASC)  COMMENT '',
  INDEX `fk_paciente_anamLyHA1_idx` (`anamnesis_lenguaje_anl_id` ASC)  COMMENT '',
  INDEX `fk_paciente_laboratorio1_idx` (`laboratorio_idlaboratorio` ASC)  COMMENT '',
  CONSTRAINT `fk_paciente_profesor`
    FOREIGN KEY (`profesor_prof_id`)
    REFERENCES `dbFono`.`profesor` (`prof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_anamLyHA1`
    FOREIGN KEY (`anamnesis_lenguaje_anl_id`)
    REFERENCES `dbFono`.`anamnesis_lenguaje` (`anl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_laboratorio1`
    FOREIGN KEY (`laboratorio_idlaboratorio`)
    REFERENCES `dbFono`.`laboratorio` (`lab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
